list1 = input("Enter some number: ")
list2 = list1.split()
list3 = [10,20,30,50,60,-2,-6,90,100,99,66,69,69,]
list4 = [ 'java','python','C','cpp']

print("list 2 = ",len(list2))
print("list 1 = ",len(list1))
list3.append(69)
list3.append(125)
print("after append list 3 = ",list3)
list3.remove(66)
print("after remove list 3 = ",list3)
list3.sort()
print("after sorting list 3 = ",list3)
list4.pop()
print("after pop list4 = ",list4)
list3.reverse()
print("after reverse list 3 = ",list3)
list4.insert(3,'compiler')
list4.insert(4,'os')
print("after insert list 4 = ",list4)
list5 = list3.copy()
print("after copy new list 5 = ",list5)
pos = list3.index(69)
print("position of 69 = ",pos)
cnt = list3.count(69)
print("after count = ",cnt)
list6 = list2+ list3+list4
print('after adding all list = ',list6)
list6.clear()
print("after clear list 6 = ",list6)